### PR TITLE
Replica, Suffix, Backend and Config functionalities

### PR DESCRIPTION
**Pull request by ioggstream**
Hi Rich,

I implemented a lot of functionalities and docs. My colleagues say the lib is quite easy to use even for people not acquainted with 389 - so I'm confident to push the changes and ask for feedback.

Anyway I would really like to ear from you, my jedi master ;)

Let me know what to change or not.

Peace,
R.

### CODE REVIEW

**Comment by richm** [comment]
Please see my comments in the individual commits

**Comment by richm** [comment]
There is a group at Red Hat working on the next generation 389 testing framework and administration library, written in python/pytest, and using some of the code from dsadmin that you worked on, and freeipa.  If you are interested, please send an email to 389-devel@lists.fedoraproject.org and I will put you in touch with the developers.  I would like you to be involved in that project.

**Comment by tbordaz** [comment]
Doing some tests with master creation it is running like a charm !! great !!
Just a note, I had to modify slightly replicaSetupAll in order to remove 'log' property from repArgs before calling conn.replica.add()

**Comment by ioggstream** [comment]
Hi Rich,

could tbordaz issue be fixed from my last push request?

Peace,
R:

**Pull request merged**
